### ISSUE TITLE
clock_gettime missing on older macos

### ISSUE THREAD

**Issue by rufty** [scipr-lab/libff#15]
Building on MacOS 10.11.6 fails with:
/Volumes/Builds/libff/libff/common/profiling.cpp:45:12: fatal error: no member named 'clock_gettime' in the global namespace
    if ( ::clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts) )

This seems to be the issue: https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

Build used macports clang++ version 5.0.1 and without procps

**Comment by ValarDragon** [comment]
I'm going to close this, its now supported on macOS version 10.12 on onwards. 

If you need support for older MacOS versions still, we can try integrating that fix.
