### ISSUE TITLE
Installing libff (via libsnark) results in awkward header structure

### ISSUE THREAD

**Issue by copumpkin** [scipr-lab/libff#16]
For example, libsnark depends on libff, and using a header from libsnark gives me the following error:

```
In file included from /nix/store/glnz76ald47lz78al77wq98my1qn6dmi-libsnark-pre9e6b19ff/include/libsnark/common/default_types/r1cs_ppzksnark_pp.hpp:16:
In file included from /nix/store/glnz76ald47lz78al77wq98my1qn6dmi-libsnark-pre9e6b19ff/include/libff/common/default_types/ec_pp.hpp:28:
In file included from /nix/store/glnz76ald47lz78al77wq98my1qn6dmi-libsnark-pre9e6b19ff/include/libff/algebra/curves/bn128/bn128_pp.hpp:10:
/nix/store/glnz76ald47lz78al77wq98my1qn6dmi-libsnark-pre9e6b19ff/include/libff/algebra/curves/bn128/bn128_g1.hpp:12:10: fatal error: 'depends/ate-pairing/include/bn.h' file not found
#include "depends/ate-pairing/include/bn.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

As far as I can tell, this is because the "public" header bn128_g1.hpp includes a header from the `depends` folder, which doesn't get installed with any of the standard scripts, so downstream packages can't use it easily without messing with their include directories.

**Comment by howardwu** [comment]
From libff, you will need to fetch the dependencies:
```
git submodule init && git submodule update
```
This is the same from libsnark. All content from the `libsnark/depends` folder are installed as part of the parent's compilation process. The parent's dependency `CMakeLists.txt` calls into all child dependencies and compiles the requisite libraries natively. See https://github.com/scipr-lab/libsnark/blob/master/depends/CMakeLists.txt

**Comment by etam** [comment]
I wanted to disagree. Here's what I did:
```bash
git clone https://github.com/scipr-lab/libff.git
cd libff
git submodule update --init
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="${PWD}/install" ..
make -j4
make install
```

The result is that in path "install/include/libff" are header from libff, but no headers from "depends" are anywhere installed.
