### ISSUE TITLE
Can size_t be 64 bits?

### ISSUE THREAD

**Issue by dimitri-xyz** [scipr-lab/libff#34]
I believe this will fail if size_t is 64 bits or more and the value is requested is also more than 2^32. 

https://github.com/scipr-lab/libff/blob/c927821ebe02e0a24b5e0f9170cec5e211a35f08/libff/common/utils.cpp#L19-L30

Adding a similar right shift of 32 bits would solve the problem for situations when size_t has 64 bits.

**Comment by ValarDragon** [comment]
Thanks for pointing this out, will fix
