### ISSUE TITLE
Maintaining the library and using "semver" to version releases

### ISSUE THREAD

**Issue by AntoineRondelet** [scipr-lab/libff#36]
*Note:* This issue is applicable to most of the [scipr-lab](https://github.com/scipr-lab) libraries.

Most of the libraries are not packaged into releases and versioned.
I believe that doing so would be a great improvement, and would ease the use of the scipr-lab libraries in other projects.

Pull Requests like: https://github.com/scipr-lab/libff/pull/35 propose breaking/incompatible API changes that aim to improve the usability of the library. If libraries were versioned using [semver](https://semver.org/#semantic-versioning-200) and released periodically, merging such PRs should lead to an increase in the `MAJOR` version in order to indicate that breaking changes have been added to the library and ease the use of the library as a dependency.
Likewise, `MINOR`, and `PATCH` should be incremented accordingly.

I am not sure it there is/are "official maintainers" for the libraries. I can see that @howardwu has been contributing most to libff/dizk, @madars has contributed most to libsnark, and @Pratyush has authored most of the Rust code. As such, have you all considered versioning and packaging releases of the libraries?

Thanks,

**Comment by madars** [comment]
Yes, this sounds excellent! We currently have no official policy but I just tagged current master as v0.9.0. @alexchmit and I intend to pull your #35 and tag the result as v1.0.0.

**Comment by AntoineRondelet** [comment]
Great! I'll close this issue now as I don't see a reason to keep it open. Please feel free to re-open it if needed.
