### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by gargarchit** [scipr-lab/libff#49]
In div_ceil utils function,  It gives, Floating point exception

https://github.com/scipr-lab/libff/blob/04094606d6e90f4d6a2d6a9d32a3a5a660b67bd4/libff/common/utils.cpp#L86

Here, we can replace the return statement by:

`return x/y + (x % y != 0)`

**Comment by ValarDragon** [comment]
The floating point exception is due to the division by zero right? As I understand it, the suggested patch wouldn't fix that. 

Perhaps we should add an if statement for y being equal to 0, and provide a more informative error.

**Comment by gargarchit** [comment]
Yeah, you are right, We need to add if statements for y == 0

**Comment by ValarDragon** [comment]
Fixed!
